toggled smart switch through local home assistant instead of via IFTT, API rehaul

diff --git a/shell-server/start-server b/shell-server/start-server
--- a/shell-server/start-server
+++ b/shell-server/start-server
@@ -1,8 +1,11 @@
 #!/bin/bash -eu
+
+source ~/.zshenv
+
 PORT=6780
 dir=$(dirname $0)
 
 echo "Starting shell-server on port ${PORT}..."
 
 # it must be an absolute path, otherwise it won't work on Mac via Automator
-/opt/homebrew/bin/php -S 0.0.0.0:${PORT} "${dir}/shell-server.php" || echo "Error, not started."; exit 1
+/opt/homebrew/bin/php -S 0.0.0.0:${PORT} "${dir}/shell-server.php" 2>&1 || echo "Error, not started."; exit 1
